### PR TITLE
fix: filter by positions and order by most actives

### LINKED ISSUE #252: Filter by POIs and sorted by most actives not working as expected
When filtering by POIs and sorted by most active, it returns 100 as total data, but the number of places is 46.

### PR DESCRIPTION
**Pull request by braianj**

### CODE REVIEW

**Review by 2fd — APPROVED** [review]

File: src/entities/Place/routes/getPlaceMostActiveList.ts [hunk 1]
```diff
@@ -59,7 +59,9 @@ export const getPlaceMostActiveList = Router.memo(
       only_featured: !!bool(query.only_featured),
       only_highlighted: !!bool(query.only_highlighted),
       positions: query.positions.length
-        ? unique([...hotScenesPositions, ...query.positions])
+        ? hotScenesPositions.filter((position) =>
```
Comment (2fd) [inline src/entities/Place/routes/getPlaceMostActiveList.ts:62]: This is a `0^2` operation, whenever you have something like this we should use a `Set` inside the filter, like:

```ts
const positions = new Set(query.positions)

hotScenesPositions.filter(position => positions.has(position))

```

**Review by 2fd — CHANGES_REQUESTED** [review]
